/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export interface CdbEntry {
  key: Buffer
  value: Buffer
}
export declare class CdbWriter {
  constructor(path: string)
  put(key: Buffer, value: Buffer): void
  finalize(): void
}
export declare class Cdb {
  static open(path: string): Cdb
  get(key: Buffer): Buffer | null
  iter(): Array<CdbEntry>
}
