/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export interface CdbEntry {
  key: Buffer
  value: Buffer
}
export declare class CdbWriterNode {
  constructor(path: string)
  put(key: Buffer, value: Buffer): void
  finalize(): void
}
export declare class CdbNode {
  static open(path: string): CdbNode
  get(key: Buffer): Buffer | null
  iter(): Array<CdbEntry>
}
