[package]
name = "cdb64-python"
version = { workspace = true }
edition = { workspace = true }

[lib]
name = "cdb64_python"
crate-type = ["cdylib"]

[dependencies]
pyo3 = { version = "0.25.0", features = ["abi3"] }
cdb64 = { workspace = true }
